import os
from xml.etree import ElementTree as ET

res_dir = "/Users/ferlagod/AndroidStudioProjects/Rocinante/app/src/main/res"
languages = {
    "ca": {"settings_appearance": "Aparença", "settings_theme": "Tema visual", "settings_theme_system": "Sistema", "settings_theme_light": "Clar", "settings_theme_dark": "Fosc", "settings_language": "Idioma", "settings_notifications": "Notificacions", "settings_notifications_desc": "Rebre notificacions locals", "settings_behavior": "Comportament", "settings_open_links": "Obrir enllaços fora de l'app", "settings_open_links_desc": "Usa el teu navegador predeterminat per veure perfils externs i altres enllaços", "settings_clear_cache": "Netejar memòria cau d'imatges", "settings_clear_cache_desc": "Alliberar espai al disc", "settings_cache_cleared": "Memòria cau netejada", "settings_about": "Quant a", "settings_version": "Versió", "settings_donate": "Donar al desenvolupador", "settings_donate_desc": "Dona suport a Rocinante a Liberapay", "settings_account": "Compte", "settings_logout": "Tancar sessió", "settings_logout_desc": "Sortiràs del teu compte actual", "settings_logout_confirm": "Estàs segur que vols tancar sessió de %1$s?", "settings_logout_confirm_btn": "Tancar sessió", "settings_logout_cancel": "Cancel·lar"},
    "cs": {"settings_appearance": "Vzhled", "settings_theme": "Vizuální téma", "settings_theme_system": "Systém", "settings_theme_light": "Světlý", "settings_theme_dark": "Tmavý", "settings_language": "Jazyk", "settings_notifications": "Oznámení", "settings_notifications_desc": "Přijímat místní oznámení", "settings_behavior": "Chování", "settings_open_links": "Otevírat odkazy mimo aplikaci", "settings_open_links_desc": "Použít výchozí prohlížeč pro externí odkazy", "settings_clear_cache": "Vymazat mezipaměť obrázků", "settings_clear_cache_desc": "Uvolnit místo na disku", "settings_cache_cleared": "Mezipaměť vymazána", "settings_about": "O aplikaci", "settings_version": "Verze", "settings_donate": "Darovat vývojáři", "settings_donate_desc": "Podpořte vývoj Rocinante", "settings_account": "Účet", "settings_logout": "Odhlásit se", "settings_logout_desc": "Budete odhlášeni", "settings_logout_confirm": "Opravdu se chcete odhlásit z %1$s?", "settings_logout_confirm_btn": "Odhlásit", "settings_logout_cancel": "Zrušit"},
    "de": {"settings_appearance": "Aussehen", "settings_theme": "Visuelles Design", "settings_theme_system": "System", "settings_theme_light": "Hell", "settings_theme_dark": "Dunkel", "settings_language": "Sprache", "settings_notifications": "Benachrichtigungen", "settings_notifications_desc": "Lokale Benachrichtigungen erhalten", "settings_behavior": "Verhalten", "settings_open_links": "Links außerhalb der App öffnen", "settings_open_links_desc": "Standardbrowser für externe Links verwenden", "settings_clear_cache": "Bilder-Cache leeren", "settings_clear_cache_desc": "Speicherplatz freigeben", "settings_cache_cleared": "Cache geleert", "settings_about": "Über", "settings_version": "Version", "settings_donate": "An den Entwickler spenden", "settings_donate_desc": "Unterstütze die Entwicklung von Rocinante", "settings_account": "Konto", "settings_logout": "Abmelden", "settings_logout_desc": "Du wirst abgemeldet", "settings_logout_confirm": "Möchtest du dich wirklich von %1$s abmelden?", "settings_logout_confirm_btn": "Abmelden", "settings_logout_cancel": "Abbrechen"},
    "el": {"settings_appearance": "Εμφάνιση", "settings_theme": "Οπτικό θέμα", "settings_theme_system": "Σύστημα", "settings_theme_light": "Φωτεινό", "settings_theme_dark": "Σκοτεινό", "settings_language": "Γλώσσα", "settings_notifications": "Ειδοποιήσεις", "settings_notifications_desc": "Λήψη τοπικών ειδοποιήσεων", "settings_behavior": "Συμπεριφορά", "settings_open_links": "Άνοιγμα συνδέσμων εκτός εφαρμογής", "settings_open_links_desc": "Χρήση του προεπιλεγμένου προγράμματος περιήγησης", "settings_clear_cache": "Εκκαθάριση προσωρινής μνήμης εικόνων", "settings_clear_cache_desc": "Απελευθέρωση χώρου", "settings_cache_cleared": "Η προσωρινή μνήμη καθαρίστηκε", "settings_about": "Πληροφορίες", "settings_version": "Έκδοση", "settings_donate": "Δωρεά στον προγραμματιστή", "settings_donate_desc": "Υποστηρίξτε το Rocinante", "settings_account": "Λογαριασμός", "settings_logout": "Αποσύνδεση", "settings_logout_desc": "Θα αποσυνδεθείτε", "settings_logout_confirm": "Είστε σίγουροι ότι θέλετε να αποσυνδεθείτε από το %1$s;", "settings_logout_confirm_btn": "Αποσύνδεση", "settings_logout_cancel": "Ακύρωση"},
    "fr": {"settings_appearance": "Apparence", "settings_theme": "Thème visuel", "settings_theme_system": "Système", "settings_theme_light": "Clair", "settings_theme_dark": "Sombre", "settings_language": "Langue", "settings_notifications": "Notifications", "settings_notifications_desc": "Recevoir des notifications", "settings_behavior": "Comportement", "settings_open_links": "Ouvrir les liens en dehors de l'application", "settings_open_links_desc": "Utiliser votre navigateur par défaut", "settings_clear_cache": "Vider le cache des images", "settings_clear_cache_desc": "Libérer de l'espace", "settings_cache_cleared": "Cache vidé", "settings_about": "À propos", "settings_version": "Version", "settings_donate": "Faire un don", "settings_donate_desc": "Soutenir Rocinante", "settings_account": "Compte", "settings_logout": "Déconnexion", "settings_logout_desc": "Vous serez déconnecté", "settings_logout_confirm": "Voulez-vous vraiment vous déconnecter de %1$s ?", "settings_logout_confirm_btn": "Déconnexion", "settings_logout_cancel": "Annuler"},
    "it": {"settings_appearance": "Aspetto", "settings_theme": "Tema visivo", "settings_theme_system": "Sistema", "settings_theme_light": "Chiaro", "settings_theme_dark": "Scuro", "settings_language": "Lingua", "settings_notifications": "Notifiche", "settings_notifications_desc": "Ricevere notifiche", "settings_behavior": "Comportamento", "settings_open_links": "Apri link fuori dall'app", "settings_open_links_desc": "Usa il browser predefinito per i link esterni", "settings_clear_cache": "Svuota cache immagini", "settings_clear_cache_desc": "Libera spazio", "settings_cache_cleared": "Cache svuotata", "settings_about": "Informazioni", "settings_version": "Versione", "settings_donate": "Fai una donazione", "settings_donate_desc": "Supporta Rocinante", "settings_account": "Account", "settings_logout": "Esci", "settings_logout_desc": "Verrai disconnesso", "settings_logout_confirm": "Sei sicuro di voler uscire da %1$s?", "settings_logout_confirm_btn": "Esci", "settings_logout_cancel": "Annulla"},
    "nl": {"settings_appearance": "Uiterlijk", "settings_theme": "Visueel thema", "settings_theme_system": "Systeem", "settings_theme_light": "Licht", "settings_theme_dark": "Donker", "settings_language": "Taal", "settings_notifications": "Meldingen", "settings_notifications_desc": "Lokale meldingen ontvangen", "settings_behavior": "Gedrag", "settings_open_links": "Links buiten de app openen", "settings_open_links_desc": "Gebruik je standaardbrowser", "settings_clear_cache": "Afbeeldingscache wissen", "settings_clear_cache_desc": "Ruimte vrijmaken", "settings_cache_cleared": "Cache gewist", "settings_about": "Over", "settings_version": "Versie", "settings_donate": "Doneren aan de ontwikkelaar", "settings_donate_desc": "Ondersteun Rocinante", "settings_account": "Account", "settings_logout": "Uitloggen", "settings_logout_desc": "Je wordt uitgelogd", "settings_logout_confirm": "Weet je zeker dat je wilt uitloggen bij %1$s?", "settings_logout_confirm_btn": "Uitloggen", "settings_logout_cancel": "Annuleren"},
    "pl": {"settings_appearance": "Wygląd", "settings_theme": "Motyw", "settings_theme_system": "System", "settings_theme_light": "Jasny", "settings_theme_dark": "Ciemny", "settings_language": "Język", "settings_notifications": "Powiadomienia", "settings_notifications_desc": "Otrzymuj powiadomienia", "settings_behavior": "Zachowanie", "settings_open_links": "Otwieraj linki poza aplikacją", "settings_open_links_desc": "Użyj domyślnej przeglądarki", "settings_clear_cache": "Wyczyść pamięć podręczną obrazów", "settings_clear_cache_desc": "Zwolnij miejsce na dysku", "settings_cache_cleared": "Pamięć wyczyszczona", "settings_about": "O aplikacji", "settings_version": "Wersja", "settings_donate": "Przekaż darowiznę", "settings_donate_desc": "Wesprzyj Rocinante", "settings_account": "Konto", "settings_logout": "Wyloguj się", "settings_logout_desc": "Zostaniesz wylogowany", "settings_logout_confirm": "Czy na pewno chcesz się wylogować z %1$s?", "settings_logout_confirm_btn": "Wyloguj", "settings_logout_cancel": "Anuluj"},
    "pt": {"settings_appearance": "Aparência", "settings_theme": "Tema visual", "settings_theme_system": "Sistema", "settings_theme_light": "Claro", "settings_theme_dark": "Escuro", "settings_language": "Idioma", "settings_notifications": "Notificações", "settings_notifications_desc": "Receber notificações", "settings_behavior": "Comportamento", "settings_open_links": "Abrir links fora do app", "settings_open_links_desc": "Usar navegador padrão", "settings_clear_cache": "Limpar cache de imagens", "settings_clear_cache_desc": "Liberar espaço", "settings_cache_cleared": "Cache limpo", "settings_about": "Sobre", "settings_version": "Versão", "settings_donate": "Doar", "settings_donate_desc": "Apoie o Rocinante", "settings_account": "Conta", "settings_logout": "Sair", "settings_logout_desc": "Você será desconectado", "settings_logout_confirm": "Tem certeza que deseja sair de %1$s?", "settings_logout_confirm_btn": "Sair", "settings_logout_cancel": "Cancelar"},
    "ro": {"settings_appearance": "Aspect", "settings_theme": "Temă", "settings_theme_system": "Sistem", "settings_theme_light": "Luminos", "settings_theme_dark": "Întunecat", "settings_language": "Limbă", "settings_notifications": "Notificări", "settings_notifications_desc": "Primește notificări", "settings_behavior": "Comportament", "settings_open_links": "Deschide linkuri în exterior", "settings_open_links_desc": "Folosește browserul implicit", "settings_clear_cache": "Golește memoria cache imagini", "settings_clear_cache_desc": "Eliberează spațiu", "settings_cache_cleared": "Cache golit", "settings_about": "Despre", "settings_version": "Versiune", "settings_donate": "Donează", "settings_donate_desc": "Susține Rocinante", "settings_account": "Cont", "settings_logout": "Deconectare", "settings_logout_desc": "Vei fi deconectat", "settings_logout_confirm": "Sigur vrei să te deconectezi de la %1$s?", "settings_logout_confirm_btn": "Deconectare", "settings_logout_cancel": "Anulare"},
    "sv": {"settings_appearance": "Utseende", "settings_theme": "Tema", "settings_theme_system": "System", "settings_theme_light": "Ljust", "settings_theme_dark": "Mörkt", "settings_language": "Språk", "settings_notifications": "Aviseringar", "settings_notifications_desc": "Ta emot aviseringar", "settings_behavior": "Beteende", "settings_open_links": "Öppna länkar utanför appen", "settings_open_links_desc": "Använd standardwebbläsaren", "settings_clear_cache": "Rensa bildcache", "settings_clear_cache_desc": "Frigör utrymme", "settings_cache_cleared": "Cachen rensad", "settings_about": "Om", "settings_version": "Version", "settings_donate": "Donera", "settings_donate_desc": "Stöd Rocinante", "settings_account": "Konto", "settings_logout": "Logga ut", "settings_logout_desc": "Du kommer att loggas ut", "settings_logout_confirm": "Är du säker på att du vill logga ut från %1$s?", "settings_logout_confirm_btn": "Logga ut", "settings_logout_cancel": "Avbryt"},
    "uk": {"settings_appearance": "Вигляд", "settings_theme": "Тема", "settings_theme_system": "Система", "settings_theme_light": "Світла", "settings_theme_dark": "Темна", "settings_language": "Мова", "settings_notifications": "Сповіщення", "settings_notifications_desc": "Отримувати сповіщення", "settings_behavior": "Поведінка", "settings_open_links": "Відкривати посилання поза додатком", "settings_open_links_desc": "Використовувати браузер за замовчуванням", "settings_clear_cache": "Очистити кеш зображень", "settings_clear_cache_desc": "Звільнити місце", "settings_cache_cleared": "Кеш очищено", "settings_about": "Про додаток", "settings_version": "Версія", "settings_donate": "Зробити пожертву", "settings_donate_desc": "Підтримати Rocinante", "settings_account": "Акаунт", "settings_logout": "Вийти", "settings_logout_desc": "Ви вийдете з акаунту", "settings_logout_confirm": "Ви впевнені, що хочете вийти з %1$s?", "settings_logout_confirm_btn": "Вийти", "settings_logout_cancel": "Скасувати"}
}

for lang, trans in languages.items():
    file_path = os.path.join(res_dir, f"values-{lang}", "strings.xml")
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
        
        if "settings_appearance" in content:
            continue
            
        insertion = "\n"
        for key, value in trans.items():
            safe_val = value.replace("'", "\\'")
            insertion += f'    <string name="{key}">{safe_val}</string>\n'
            
        content = content.replace("</resources>", insertion + "</resources>")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
            
print("Done")
